# Generated by Django 4.2.25 on 2025-10-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tryhackme_user_id',
            field=models.CharField(blank=True, default='728215', max_length=100),
        ),
    ]
