# Generated by Django 4.2.25 on 2025-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_tryhackme_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
